version: 2

jobs:
  build:
    docker:
      - image: mojdigitalstudio/git-secrets-ahoy 
    working_directory: /git
    steps:
      - checkout
      - run:
          name: Run truffleHog
          command: |
            git checkout -b "${CIRCLE_BRANCH}" # give the current checkout a name
            /trufflehog/truffleHogger.sh --use_current_branch  --since_commit "$(git rev-parse HEAD~20)" 
