name: plan iis stage

on:
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - master
    paths:
      - iis/stage/*
      - shared/apps/iis.tf
      - azure-devtest.tf
      - ips.tf

env:
  GITHUB_ORGANIZATION: ministryofjustice
  ENVIRONMENT: iis/stage
  GITHUB_USERNAME: hmpps-dso-automation
  GITHUB_TOKEN: ${{ secrets.DSO_GITHUB_AUTOMATION_PAT }}
  WORKING_DIRECTORY: iis/stage
  ARM_CLIENT_ID: b11478e9-3ca6-40b8-bbcd-9cb46c02957c # digital-studio-infra-devtest
  ARM_CLIENT_SECRET: ${{ secrets.DIGITAL_STUDIO_INFRA_DEVTEST }} 
  ARM_SUBSCRIPTION_ID: c27cfedb-f5e9-45e6-9642-0fad1a5c94e7 # Digital Studio Dev & Test Environments
  ARM_TENANT_ID: 747381f4-e81f-4a43-bf68-ced6a1e14edf

jobs:
  verify-terraform-config:
    runs-on: ubuntu-latest
    environment: env.ENVIRONMENT

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GitHub credential.helper for terraform
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: https://${{ env.GITHUB_USERNAME }}:${{ env.GITHUB_TOKEN }}@github.com
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.9

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform init

      - name: terraform validate
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform validate

      - name: terraform fmt
        if: ${{ github.event_name == 'pull_request' }}
        working-directory: ${{ env.WORKING_DIRECTORY }}
        id: format
        run: |
          terraform fmt > tf_fmt.txt
          fmt=$(wc -l tf_fmt.txt | awk '{print $1;}')
          if [[ $fmt -gt 0 ]]; then
            echo 'TF_FMT<<EOF' >> $GITHUB_ENV
            cat tf_fmt.txt >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
            exit 1
          fi

      - name: Post a PR comment with the files that need fomatting
        if: ${{ github.event_name == 'pull_request' && failure() }}
        uses: allthatjazzleo/actions-pull-request-add-comment@master
        with:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          message: "The following files need formatting in ${{ env.ENVIRONMENT }} environment: \n```\n${{ env.TF_FMT }}\n```"

      - name: terraform refresh
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          terraform refresh

      - name: terraform plan
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          terraform plan -out=tf.plan -refresh=false -no-color > tf_out.txt
          tail -c 65476 tf_out.txt > tf_plan.txt
          cat tf_plan.txt
          echo 'TF_PLAN_OUT<<EOF' >> $GITHUB_ENV
          cat tf_plan.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      
      - name: Post a PR comment with the terraform plan output
        if: ${{ github.event_name == 'pull_request' }}
        uses: allthatjazzleo/actions-pull-request-add-comment@master
        with:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          message: "Terraform plan output in ${{ env.ENVIRONMENT }} environment: \n```\n${{ env.TF_PLAN_OUT }}\n```"

      - name: Post a post merge PR comment with the terraform plan output
        if: ${{ github.event.pull_request.merged || github.event_name == 'push' }}
        uses: guchaocharlie/comment-pr@v1
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          comment: "Terraform plan output in ${{ env.ENVIRONMENT }} environment: \n```\n${{ env.TF_PLAN_OUT }}\n```"
